services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: always
    container_name: palworld-server
    stop_grace_period: 30s
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=8211
      - PLAYERS=16
      - SERVER_PASSWORD=*****
      - MULTITHREADING=true
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - TZ=UTC
      - DIFFICULTY=Normal
      - PAL_EGG_DEFAULT_HATCHING_TIME=5.000000
      - DEATH_PENTALTY=Item
      - ADMIN_PASSWORD=*****
      - COMMUNITY=false
      - SERVER_NAME=*****
      - SERVER_DESCRIPTION=*****
      - AUTO_UPDATE_ENABLED=true
    volumes:
      - ./palworld:/palworld/